export const GET_ALL_GENRES = "GET_ALL_GENRES";
export const ADD_GENRE = "ADD_GENRE";
export const EDIT_GENRE = "EDIT_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";

export const GET_ALL_PLANS = "GET_ALL_PLANS";
export const ADD_PLAN = "ADD_PLAN";
export const EDIT_PLAN = "EDIT_PLAN";
export const DELETE_PLAN = "DELETE_PLAN";

export const GET_ALL_MANAGERS = "GET_ALL_MANAGERS";
export const ADD_MANAGER = "ADD_MANAGER";
export const EDIT_MANAGER = "EDIT_MANAGER";
export const DELETE_MANAGER = "DELETE_MANAGER";

export const GET_ALL_SEASONS = "GET_ALL_SEASONS";
export const ADD_SEASON = "ADD_SEASON";
export const EDIT_SEASON = "EDIT_SEASON";
export const DELETE_SEASON = "DELETE_SEASON";
export const GET_SEASONS_BY_SERIES_ID = "GET_SEASONS_BY_SERIES_ID";

export const GET_ALL_EPISODES = "GET_ALL_EPISODES";
export const ADD_EPISODE = "ADD_EPISODE";
export const EDIT_EPISODE = "EDIT_EPISODE";
export const DELETE_EPISODE = "DELETE_EPISODE";
export const GET_EPISODES_BY_SEASON_ID = "GET_EPISODES_BY_SEASON_ID";

export const GET_ALL_SUBTITLES = "GET_ALL_SUBTITLES";
export const ADD_SUBTITLE = "ADD_SUBTITLE";
export const EDIT_SUBTITLE = "EDIT_SUBTITLE";
export const DELETE_SUBTITLE = "DELETE_SUBTITLE";
export const GET_SUBTITLES_BY_MOVIE_ID = "GET_SUBTITLES_BY_MOVIE_ID";
export const GET_SUBTITLES_BY_EPISODE_ID = "GET_SUBTITLES_BY_EPISODE_ID";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const EDIT_CUSTOMER = "EDIT_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";

export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";

export const GET_ALL_SERIES = "GET_ALL_SERIES";
export const ADD_SERIES = "ADD_SERIES";
export const DELETE_SERIES = "DELETE_SERIES";
export const EDIT_SERIES = "EDIT_SERIES";

export const GET_ALL_SUBS = "GET_ALL_SUBS";
export const GET_SUBS_BY_CUSTOMER_ID = "GET_SUBS_BY_CUSTOMER_ID";
export const DELETE_SUB = "DELETE_SUB";

export const SET_USER_ROLE = "SET_USER_ROLE";
export const GET_USER_ROLE = "GET_USER_ROLE";

export const SET_LOADING = "SET_LOADING";
export const CLEAR_LOADING = "CLEAR_LOADING";